version: '3.8'

services:
  backend:
    build:
      context: ./clinic-appointment-api
    container_name: myapp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: myapp-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sahti_db
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: